services: 
  mysql_ctn:
    build:
      context: .
      dockerfile: Dockerfile.initial_db
    container_name: mysql_ctn
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-home_db}
      MYSQL_USER: ${MYSQL_USER:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme_db_password}
    volumes:
      - mysql_vol:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - app_net

networks:
  app_net:

volumes:
  mysql_vol:
